import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { convexTest } from "convex-test";
import schema from "../convex/schema";
import { internal } from "../convex/_generated/api";
const modules = import.meta.glob("../convex/**/*.ts");
beforeEach(() => { vi.useFakeTimers(); vi.stubEnv("REQUEST_AUTOMATION_ENABLED", "true"); });
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers(); vi.unstubAllEnvs(); });
test("anonymous generation is resumable; purchase atomically adds contact and notifies only the owner", async () => {
  const t = convexTest(schema, modules);
  const input = { requestId: "#anonymous", requestType: "mvp" as const, idea: "Сайт магазина инструментов", contactMethod: "none" as const, contact: "", accessTokenHash: "a".repeat(64), adminTokenHash: "b".repeat(64), receivedAt: Date.now(), source: { utmSource: "test", utmCampaign: "", utmContent: "", utmTerm: "", referrer: "" }, ownerNotificationText: "LOCAL TEST anonymous request" };
  expect((await t.mutation(internal.requests.store, input)).created).toBe(true);
  expect((await t.mutation(internal.requests.store, { ...input, requestId: "#retry" })).created).toBe(false);
  expect(await t.query(internal.automation.summary, { accessTokenHash: input.accessTokenHash })).toMatchObject({ phase: "queued", canBuy: false });
  const job = await t.mutation(internal.automation.claim, { protocol: 2, leaseToken: "x".repeat(40), requestId: input.requestId });
  expect(job?.idea).toBe(input.idea);
  expect(await t.run(ctx => ctx.db.query("requestJobs").take(10))).toHaveLength(1);
  await t.run(async ctx => { const state = await ctx.db.query("requestAutomations").first(); await ctx.db.patch(state!._id, { phase: "review", demoOptions: [{ id: "1", title: "Магазин", demoUrl: "https://demo.example.org/1/" }] }); });
  const buy = { accessTokenHash: input.accessTokenHash, kind: "offer_purchase_requested" as const, demoId: "1" as const, hosting: "cloudflare" as const, purchase: "source" as const, offerVariant: "standard" as const };
  expect((await t.mutation(internal.automation.clientAction, buy)).ok).toBe(false);
  expect((await t.mutation(internal.automation.clientAction, { ...buy, contactMethod: "email", contact: "invalid" })).ok).toBe(false);
  expect((await t.mutation(internal.automation.clientAction, { ...buy, accessTokenHash: "wrong", contactMethod: "telegram", contact: "@local_test" })).ok).toBe(false);
  expect(await t.run(ctx => ctx.db.query("mvpRequests").first())).toMatchObject({ contactMethod: "none", contact: "" });
  const valid = { ...buy, contactMethod: "telegram" as const, contact: " @local_test " };
  expect((await t.mutation(internal.automation.clientAction, valid)).ok).toBe(true);
  expect((await t.mutation(internal.automation.clientAction, valid)).ok).toBe(true);
  expect(await t.query(internal.automation.summary, { accessTokenHash: input.accessTokenHash })).toMatchObject({ sourcePurchaseRequested: true, purchaseContact: { method: "telegram", value: "@local_test" } });
  const events = await t.run(ctx => ctx.db.query("requestEvents").take(10));
  expect(events.filter(e => e.kind === "offer_purchase_requested")).toHaveLength(1);
  expect(events.find(e => e.kind === "offer_purchase_requested")?.text).toContain("@local_test");
  expect(events.filter(e => e.kind === "request_received")).toHaveLength(1);
  expect(events.filter(e => e.kind === "generation_started")).toHaveLength(1);
  expect(await t.run(ctx => ctx.db.query("requestDeliveries").take(10))).toHaveLength(0);
});
