-- Import into a dedicated database using phpMyAdmin. Never import over an existing site.
CREATE TABLE pf_settings (id INT PRIMARY KEY, key_hash CHAR(64) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO pf_settings VALUES (1,NULL);
CREATE TABLE pf_content (id INT PRIMARY KEY, version INT NOT NULL, json LONGTEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pf_assets (id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY, type VARCHAR(40) NOT NULL, bytes LONGBLOB NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pf_sessions (hash CHAR(64) CHARACTER SET ascii PRIMARY KEY, expires BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pf_limits (name VARCHAR(40) PRIMARY KEY, tokens DOUBLE NOT NULL, updated BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pf_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, event VARCHAR(255) NOT NULL, created BIGINT NOT NULL, version INT UNIQUE NULL, json LONGTEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
