<?php
// Copy as config.php OUTSIDE public_html. Use values from the hosting panel.
return [
    'dsn' => 'mysql:host=localhost;dbname=ACCOUNT_portfolio;charset=utf8mb4',
    'user' => 'ACCOUNT_portfolio',
    'password' => 'REPLACE_DATABASE_PASSWORD',
    'origin' => 'https://YOUR-SITE.example',
    // SHA-256 of the random 43-character installation/admin key; generated by packager.
    // Used ONLY for initial installation, never overrides a subsequently rotated key.
    'setup_key_hash' => 'REPLACE_WITH_GENERATED_HASH',
];
