import {existsSync,lstatSync,readdirSync,realpathSync,readFileSync,writeFileSync,mkdirSync,mkdtempSync,renameSync,rmSync,chmodSync} from 'node:fs';
import {resolve,join,basename,dirname} from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
const marker='# Lazysoft portable portfolio — generated by setup.mjs';
export function runtimeSupported(version=process.versions.node){const [major,minor]=version.split('.').map(Number);return major===22&&minor>=5||major===24}
export function listSites(home){
 const root=join(home,'domains');if(!existsSync(root)||lstatSync(root).isSymbolicLink())return [];
 return readdirSync(root).filter(name=>{const p=join(root,name);return !name.startsWith('.')&&lstatSync(p).isDirectory()&&!lstatSync(p).isSymbolicLink()}).map(name=>join(root,name));
}
export async function verifyHttps(origin){
 const r=await fetch(origin,{redirect:'manual',signal:AbortSignal.timeout(15000)});
 // HTTP errors on the old placeholder are OK; certificate validation is not optional.
 await r.body?.cancel();return true;
}
export async function install({appRoot,siteRoot,origin,runtime=process.execPath,replace=false,checkHttps=verifyHttps}){
 if(!runtimeSupported())throw Error('Нужен node22 версии 22.5 или новее. Не используйте команду node без номера.');
 appRoot=realpathSync(appRoot);siteRoot=realpathSync(siteRoot);
 if(/[\r\n"\0]/.test(appRoot+siteRoot+runtime))throw Error('В пути к папке есть неподдерживаемые символы.');
 const url=new URL(origin);if(url.protocol!=='https:'||url.origin!==origin)throw Error('Укажите HTTPS-адрес без слеша в конце, пути и пароля.');
 const publicRoot=join(siteRoot,'public_html');
 if(appRoot===siteRoot||appRoot===publicRoot||appRoot.startsWith(publicRoot+'/'))throw Error('Папка portfolio должна находиться в корне аккаунта, НЕ внутри public_html.');
 if(existsSync(publicRoot)&&(!lstatSync(publicRoot).isDirectory()||lstatSync(publicRoot).isSymbolicLink()))throw Error('public_html — не обычная папка. Автоматическая замена остановлена.');
 const htaccess=join(publicRoot,'.htaccess');
 if(existsSync(htaccess)&&readFileSync(htaccess,'utf8').startsWith(marker)&&existsSync(join(appRoot,'hosting.json'))){
  const c=JSON.parse(readFileSync(join(appRoot,'hosting.json'),'utf8'));
  if(c.publicRoot===publicRoot&&c.publicOrigin===origin)return {alreadyInstalled:true,origin};
 }
 for(const name of ['hosting.json','node22-launcher.sh','ADMIN-KEY.txt'])if(existsSync(join(appRoot,name)))throw Error(name+' уже существует. Повторная установка не заменяет работающие настройки или ключи.');
 if(existsSync(publicRoot)&&readdirSync(publicRoot).length&&!replace)throw Error('В public_html есть файлы. Нужен выбор сохранения прежней папки. Ничего не заменено.');
 if(!existsSync(runtime))throw Error('Не найден исполняемый файл Node.js.');
 await checkHttps(origin);
 const {openDatabase,initializeKey}=await import('./server.mjs');
 const {DatabaseSync,backup}=await import('./sqlite-compat.mjs');
 const dataDir=join(appRoot,'data');
 if(existsSync(dataDir)&&lstatSync(dataDir).isSymbolicLink())throw Error('data не должна быть ссылкой.');
 mkdirSync(dataDir,{recursive:true,mode:0o700});chmodSync(dataDir,0o700);
 if(existsSync(join(dataDir,'portfolio.sqlite'))&&lstatSync(join(dataDir,'portfolio.sqlite')).isSymbolicLink())throw Error('База не должна быть ссылкой.');
 const db=openDatabase(dataDir),created=[];
 let stage,oldPublic,activated=false,createdKeyHash;
 try{
  if(db.prepare('PRAGMA quick_check').get().quick_check!=='ok')throw Error('Проверка базы не прошла. Используйте исправную копию.');
  if(db.prepare('SELECT id FROM settings').get())throw Error('В базе уже есть ключ доступа. Установка не заменяет действующий ключ.');
  const preflight=mkdtempSync(join(dataDir,'preflight-'));chmodSync(preflight,0o700);
  try{
   const trial=new DatabaseSync(join(preflight,'check.sqlite'));
   try{
    if(trial.prepare('PRAGMA journal_mode=WAL').get().journal_mode!=='wal')throw Error('Диск не поддерживает SQLite WAL.');
    trial.exec("CREATE TABLE check_data(value TEXT); INSERT INTO check_data VALUES('ok')");
    await backup(trial,join(preflight,'copy.sqlite'));
    const copy=new DatabaseSync(join(preflight,'copy.sqlite'));try{if(copy.prepare('SELECT value FROM check_data').get().value!=='ok')throw Error('Копия не прошла проверку.')}finally{copy.close()}
   }finally{trial.close()}
  }finally{rmSync(preflight,{recursive:true,force:true})}
  const key=randomBytes(32).toString('base64url');createdKeyHash=createHash('sha256').update(key).digest('hex');
  const put=(name,body,mode)=>{const p=join(appRoot,name);writeFileSync(p,body,{mode,flag:'wx'});chmodSync(p,mode);created.push(p)};
  put('ADMIN-KEY.txt',key+'\n',0o600);
  put('hosting.json',JSON.stringify({publicOrigin:origin,publicRoot,nodeExecutable:runtime},null,2)+'\n',0o600);
  const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
  put('node22-launcher.sh','#!/bin/sh\nexec '+quote(runtime)+' --experimental-sqlite "$@"\n',0o755);
  mkdirSync(join(appRoot,'tmp'),{recursive:true});
  writeFileSync(join(appRoot,'tmp/restart.txt'),'');
  initializeKey(db,dataDir,key);
  stage=mkdtempSync(join(siteRoot,'.portfolio-public-'));chmodSync(stage,0o755);
  writeFileSync(join(stage,'.htaccess'),`${marker}
Options -Indexes -MultiViews
Require all granted
SetEnv GHOST_NODE_VERSION_CHECK false
PassengerEnabled on
PassengerAppType node
PassengerAppRoot "${appRoot}"
PassengerStartupFile passenger.cjs
PassengerNodejs "${join(appRoot,'node22-launcher.sh')}"
PassengerAppEnv production
PassengerResolveSymlinksInDocumentRoot on
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^ ${origin}%{REQUEST_URI} [R=302,L,NE]
<Files ".htaccess">
Require all denied
</Files>
`,{mode:0o644});
  if(existsSync(publicRoot)){oldPublic=join(siteRoot,'public_html.before-portfolio-'+Date.now());renameSync(publicRoot,oldPublic)}
  try{renameSync(stage,publicRoot)}catch(e){if(oldPublic)renameSync(oldPublic,publicRoot);oldPublic=null;throw e}
  activated=true;
  return {origin,publicRoot,oldPublic,keyFile:join(appRoot,'ADMIN-KEY.txt'),version:db.prepare('SELECT version FROM content').get()?.version??0};
 }catch(e){
  if(!activated){
   if(createdKeyHash)db.prepare('DELETE FROM settings WHERE key_hash=?').run(createdKeyHash);
   for(const p of created.reverse())rmSync(p,{force:true});
   if(stage&&existsSync(stage))rmSync(stage,{recursive:true,force:true});
  }
  throw e;
 }finally{db.close()}
}
